consulx1:
  image: consul
  ports:
    - "8500:8500" # GUI/management

vertx:
  image: luizvilelamarques/consul-vertx
  environment:
    - porta=2220
  links:
    - consulx1
  ports:
    - "2220:2220"


#registrator:
#  image: gliderlabs/registrator:v6
#  volumes:
#    - /var/run/docker.sock:/tmp/docker.sock
#  command: "consul://consulx1:8500 -h"
#  links:
#    - consulx1

fabio:
  image: fabiolb/fabio
  volumes:
    - $PWD/fabio/fabio.properties:/etc/fabio/fabio.properties
  links:
    - consulx1
  ports:
    - "9998:9998" # GUI/management
    - "9999:9999" # HTTP exposed
